input = """
mgdsdwqulhrinkatfjoyzxcbvq
megsdwpulhrinkasfjdyzxcbvk
megsdwpulhmibkatfjoyzccbvq
megsdwtuohrinkatfjoyzecbvq
megsdwpulhdinkatfyoyzxcbvb
megszwpulhrirkatfjoyexcbvq
eegsdwpulhzinkatfjoyzxdbvq
megsdwpulhginkatfjoyqucbvq
leqsdwpulhrinkatfeoyzxcbvq
megsdwpblhrandatfjoyzxcbvq
megrdwpudhrinvatfjoyzxcbvq
mlgsdwpulhrinkatfuoyzxcbyq
mensdwpunhrinsatfjoyzxcbvq
megsdwpnlhrinqatfjoyzxcbuq
megsdwpnlhrinkatfqoysxcbvq
megsdwpulhrinkjtfjoywxobvq
megsdwpclhbinkaffjoyzxcbvq
mersdwpulhrinkattjoyzxcbdq
megsddpwohrinkatfjoyzxcbvq
mejsdwpulhrinratfjoyzxcbvl
megsdwpujhrinkatfjkbzxcbvq
megsdwpujhrinkatfjoyircbvq
megsdwgulhrinkatojoyzxcbvm
qegsdwpulhrinkatfjoyzxggvq
megsdwpflhrinkatfjsazxcbvq
megsdwpulhridkagfjoyzzcbvq
mejsdwpulhriykatfjoyyxcbvq
measdwpulhriakatfjoyzacbvq
mebsdwpulhrinkatfjoyzxmyvq
megsdwpflnrinkatfjoyzxcbxq
megsdwpulhxinuatfjoytxcbvq
megsdwsflhrinkatfjoyzxcmvq
megsdwpuuhritkarfjoyzxcbvq
megsdwpulhrinkazfjoyexcjvq
megsdwpulhrifkatfjokzxcbvc
megsdwmulvrinkatfjoyzxcblq
meggdwpulhrfnkatfjoybxcbvq
megsdwptlhrindatyjoyzxcbvq
megsdwpulhrinkauqjoyzxibvq
megsdwddlhrifkatfjoyzxcbvq
megddwpulhrinkagfjoyzxcbva
messdupulhrinkatfjoyzxqbvq
megsdwpuahrinkatfjotzxchvq
megsewpulhrankathjoyzxcbvq
megsdwpulhrinkatfjoynqcbvv
megsdwpulhrifkatfjotzxcbtq
megsdjpulcrinkitfjoyzxcbvq
fefsowpulhrinkatfjoyzxcbvq
megsdwpulapinkatfjoyzvcbvq
mejsdwpularinkatfjonzxcbvq
megsxwpllrrinkatfjoyzxcbvq
megsdlpulxvinkatfjoyzxcbvq
megsdwpulhriekztfjoyzxxbvq
megspwpulhrinuatfjoyzxcgvq
megqdwpulhrinkatfjoyzujbvq
megsdtpuehrinkatfjoyzxtbvq
megsdwjulhrmnmatfjoyzxcbvq
megjdwpulhrinkztfjoyzpcbvq
megsdwpuljrinkawfjlyzxcbvq
mewsdwpulhtinkatfjodzxcbvq
megsdwpulhrinkatfcoizxcmvq
meisdwpulhrinkatawoyzxcbvq
megshwpulhrinkatfjoyzxcbtz
megsdwpulhfinkatfjowzxcbvj
megodwpulhrcskatfjoyzxcbvq
megydxpulhrinkatfjofzxcbvq
megsdwpulhrinkatljoytxdbvq
mwgsdwpulyrinkatfjoyzxvbvq
meesdwpulhrinkatfjcwzxcbvq
cegsdwpwlhrinkatfioyzxcbvq
megsdwpulhrinkatfqhyxxcbvq
megsrrpulhrxnkatfjoyzxcbvq
megsdgpulhrinkatfjoypxcbnq
xegsdwpulhrinkaxkjoyzxcbvq
mngsdwpulhrenkatfjofzxcbvq
mecsdwpulhrinkabfjoozxcbvq
pegsdkpulhrinkatfuoyzxcbvq
megpdwpughrinkatfjoyzxzbvq
mxgrdwpulhrinyatfjoyzxcbvq
megsdwpulhpigkatfjoyzxcbfq
mhgsdwpulhrinkagfjoxzxcbvq
megsdwpblhtinkatfjqyzxcbvq
megsawvulhrinkatfjoyzxcfvq
metsuwpulhrinkatfjowzxcbvq
mexsdwpulhrinkatsjoyzxvbvq
megtdwpulhrinkatfjoizxcpvq
megidwpjlhrinkatfdoyzxcbvq
megsdwpuljrivkatfjoyqxcbvq
mespdppulhrinkatfjoyzxcbvq
megsdcpulhminkatftoyzxcbvq
megsdwpulhriskatfjayzlcbvq
mejsdwpulhrinkatfvoyzxibvq
megfdwputhriykatfjoyzxcbvq
megsdwparhrinkbtfjoyzxcbvq
mtgsdwpulhmingatfjoyzxcbvq
megsdwjulhrinkatfjtyzxtbvq
megsvwpulhrinkatfjoyzecbvf
megsdwpulprinkatyqoyzxcbvq
zegsdwpulhwinkatfjoyzxcfvq
megsdwiulhrinkatfjoyzxcjcq
aegsdwpulirinkatfjoyvxcbvq
mepsdwculbrinkatfjoyzxcbvq
msgsdcpulhrinkctfjoyzxcbvq
megsdwpulhrinkatfjoozxfevq
megscwpulhrinkatmjoyzxcbsq
megsdwpulhrinkltfjoyzxtmvq
megsddpulhrixkatfjyyzxcbvq
megsdwpulhrinkctfjoqzhcbvq
megsbapblhrinkatfjoyzxcbvq
megsdwpulhrinkatfjoyyxgpvq
mwpsdwpulhrinkutfjoyzxcbvq
megsdwpulhrinvnlfjoyzxcbvq
megsdwsulorinkakfjoyzxcbvq
mbgsdwpulhrinkktfjoyzxcbvg
megddwpulhrindatfjoyzxcbvr
memsdwpulhrinkatqjoyzxcbvo
megsdwpulbrinkarfjoyzxcbxq
megsdwpulhrilkatfjoynxcgvq
mxgsdzpulhrinkatfjoydxcbvq
megsawpulhrinkotfjoyzacbvq
measdwpulhrinkctvjoyzxcbvq
medsdwpulhtinkaqfjoyzxcbvq
megsdwsulhrknkatfjoylxcbvq
megadwpulhrinkatfjkyzxcbvh
mygsdwpulhrinkatfboyzxcavq
megsdwpulhrinkaufjxyzccbvq
mtgsdwpulhrunkatfkoyzxcbvq
megsdwpulhrinkamfwryzxcbvq
meesdwpulhrgnkatnjoyzxcbvq
megddwpolhrinkatfjoyixcbvq
megsdwpulhrinsatfjoyzicwvq
mmgsdwpulhrinkltfjoyzxcgvq
meisdwpulhhinkatfjoyzxubvq
megpdwpulhrinkatfroyzxcbkq
megszwpuhhrinkatfjoyzxcbzq
mersdwpulhrikcatfjoyzxcbvq
mjgsdwpulhrinratfjoyzxcbvl
megsdwnulkxinkatfjoyzxcbvq
megsdwpulhrinkatlaoyzxpbvq
megsdwpulhribkitfjjyzxcbvq
megsdwpzlhrinkalfjoyzkcbvq
megsdwpulhrinkutfjoyzxcdnq
mfgpdwputhrinkatfjoyzxcbvq
oegshwpclhrinkatfjoyzxcbvq
megvdwxulhrinkatfjowzxcbvq
mrgydwpulhrinkatfjoyzxcbvl
megsdwpuqhrinkaxfjoyzxcbfq
megsdwpughrinixtfjoyzxcbvq
megsdwpslxrinkatfjoyzxcbvl
megsdwpukhrinkatfjovzxnbvq
megsdwpulnrinkrtojoyzxcbvq
megsdwpuvhrinkatfjjyzxclvq
vegrdwpulhrinzatfjoyzxcbvq
melsdwwulvrinkatfjoyzxcbvq
megsdwpulhrizkbtfjoyzjcbvq
megsdwpulhrinlatfjoyzkcbvr
megsdweulhrinkaofqoyzxcbvq
megsdcpulhrifkatfdoyzxcbvq
negsdwpulhainkztfjoyzxcbvq
megsdwpklhrinkttfjoyzxvbvq
megsdwpothrdnkatfjoyzxcbvq
megsdwpulvrinkatfaoyzxcbvr
mewsdwpulhrinkatfooyzxtbvq
megtdwpulhrinkatfxoyzxcbvy
zegsdwpulhrinkamljoyzxcbvq
mkgodwpulhrcnkatfjoyzxcbvq
megsdepularinkatfjoyzxybvq
segsdwpulhrinkatfmoyzycbvq
mbgsdwpulhrsnkztfjoyzxcbvq
megsdwpmlhrinkatfjxyzhcbvq
megsdwpulhrinkatfboyqxmbvq
megsdwpulhrinkadtpoyzxcbvq
megsdmpulhrjnkatfjoyzxwbvq
megsdwpulhrivkatfroywxcbvq
megsdwdulhrinkatpjwyzxcbvq
megsdwpylhrdrkatfjoyzxcbvq
megsdwpulhrvnkptfjoyzlcbvq
megsdwpuihridkatfjuyzxcbvq
megsdwpulhbiikatfjxyzxcbvq
meggdwpulurinkatfjoyaxcbvq
mehsnwpulcrinkatfjoyzxcbvq
megsdwpulhrinkatfjoczdclvq
megsdwjulhrinkatfhkyzxcbvq
megsdwpulhrinoatfjoyzxcwvy
megpdwpelhrfnkatfjoyzxcbvq
megsjwpulhrwnkatfjdyzxcbvq
megsdwpulhrbniatfjoyzxcbpq
megsdwpulhrwnkatfjoydxcpvq
megsdwrulhrinkatfjvyixcbvq
yegvdwpulhtinkatfjoyzxcbvq
meosdwpulhrinkatfjhyzxsbvq
mjgsdwpulhrinkatfjoyyxcjvq
megsdwpulhrinkatfnoyzlmbvq
mehsdfkulhrinkatfjoyzxcbvq
megsdwpuahrinkatfyoyzxcwvq
megsdwpulhyinkatfjobzkcbvq
megsdwpjlhrinkatfnoyzscbvq
megsdwiulhrinqatfjoyzxcavq
megsdwpulurinkatfjoykxcbmq
megsdwpmlhvinkatfjotzxcbvq
megswwpulhrinfatfjoytxcbvq
mxgsdwpulhrrnkatfjoyhxcbvq
megubwpulhrinkaafjoyzxcbvq
megsdwpulhrdnsztfjoyzxcbvq
megsdwpulhronkgtfjhyzxcbvq
megsdwzulhfinratfjoyzxcbvq
megsdwpulhrinkrtfjqyixcbvq
megspwpulhrinkatfjoywxcavq
megmfjpulhrinkatfjoyzxcbvq
lelsdwpulhrinsatfjoyzxcbvq
megsdwnultrinkatfjoyzxybvq
megsdwpulhdnnkatfjpyzxcbvq
megsdwpulhzinkatfjoyzhcpvq
megoddpulhrilkatfjoyzxcbvq
megsdvpulhrwnkatfjoyzxcbdq
megsdwpulhmikkatfjoyzxcbvr
meesdwpulhrinkaofjoazxcbvq
megndwhulhrinfatfjoyzxcbvq
megsdwpulhjihkatfjoyzxcbvb
jegsdwpulhrinkattjoszxcbvq
megsdwpulhrenkatfjodzxcbvp
mefsdwpulhrinkatfjoyzxcczq
megsdwpulhrknkatfjovzxcbvb
megytwpulhrinkatfjoyzxcbvo
csgsdwpulhrinkatdjoyzxcbvq
megsbwpulhrinkazfjtyzxcbvq
mrgsdwpulhjinkatfjoyzxcbvm
megsywzulhrinkatfjofzxcbvq
megxdwpulhrndkatfjoyzxcbvq
mcgsdwpuphrixkatfjoyzxcbvq
megsdlpulxvinkatfvoyzxcbvq
megsdwpulhrinfatfjoyzicbvo
megwgwpulhrinpatfjoyzxcbvq
mggsdwpulhrinkatfjtrzxcbvq
msgsdwpulirinkatfjoyzxcbaq
megsdwpulhrineatfeoyzxcbvl
megsdnpulhrinkatojoyzxcbvb
mfgsdwpulhdinkatmjoyzxcbvq
megsdwpulhrinkawfjuyzxcbvg
megsdwpulhrincatfjoyzxcxvu
mevsdwzplhrinkatfjoyzxcbvq
megskweulhfinkatfjoyzxcbvq
mebsdvpulhrinkatfjoyzxcbkq
megddwiulhrinkatfioyzxcbvq
mygsdwpulhqinkatfooyzxcbvq
megsdweulhrfnkatfjoybxcbvq
mrgsdhpulmrinkatfjoyzxcbvq
megsdwkukhrinkatftoyzxcbvq
megsqwpulhrinfatfjoyzxebvq
megsdwpulhriskanfjoyzxctvq
"""

test = """
abcdef
bababc
abbcde
abcccd
aabcdd
abcdee
ababab
"""

from collections import Counter 

def chk(input, looking_for):
  cnt = Counter()
  for char in input:
    cnt[char] += 1
    
  count = 0  
  for k in list(cnt):
    if cnt[k] == looking_for:
      return True
      
  return False
  
assert(chk("abc", 2) == False)
assert(chk("aac", 2) == True)

def day2_1(input):
  twos = 0
  threes = 0
  for row in input.split():
    if chk(row, 2): twos += 1
    if chk(row, 3): threes += 1
    
  return twos * threes

assert(day2_1(test) == 12)  

print (day2_1(input))